export const GET_DASHBOARD_SUMMARY = 'GET_DASHBOARD_SUMMARY';
export const GET_DASHBOARD_CHARTS_DATA = 'GET_DASHBOARD_CHARTS_DATA';
export const GET_PROGRAMMES = 'GET_PROGRAMMES';
export const CREATE_PROGRAMMES = 'CREATE_PROGRAMMES';
export const DELETE_PROGRAMME = 'DELETE_PROGRAMME';
export const EDIT_PROGRAMME = 'EDIT_PROGRAMME';
