export const ADD_SMS_MESSAGE = 'ADD_SMS_MESSAGE';
export const FETCH_SMS_MESSAGE = 'FETCH_SMS_MESSAGE';
export const FETCH_ALL_SMS_LOGS = 'FETCH_ALL_SMS_LOGS';
export const FETCH_ALL_INCOMING_SMS_LOGS = 'FETCH_ALL_INCOMING_SMS_LOGS';
export const DOWNLOAD_SMS_LOGS = 'DOWNLOAD_SMS_LOGS';
export const EXPORT_SMS_LOGS_TABLE = 'EXPORT_SMS_LOGS_TABLE';
export const EXPORT_RESPONSE_LOGS = 'EXPORT_RESPONSE_LOGS';
