export const GET_SMS_TRANSACTIONS_REP = 'GET_SMS_TRANSACTIONS_REP';
export const GET_ALL_TRANSACTIONS = 'GET_ALL_TRANSACTIONS';
export const GET_SMS_TRANSACTIONS_ADMIN = 'GET_SMS_TRANSACTIONS_ADMIN';
export const APPROVE_SMS_TRANSACTIONS = 'APPROVE_SMS_TRANSACTIONS';
export const RESOLVE_SMS_TRANSACTIONS = 'RESOLVE_SMS_TRANSACTIONS';
export const PROCESS_SMS_TRANSACTIONS = 'PROCESS_SMS_TRANSACTIONS';
export const TRIGGER_SMS_RESEND_TRANSACTIONS = 'TRIGGER_SMS_RESEND_TRANSACTIONS';
export const GET_FLAGGED_TRANSACTIONS = 'GET_FLAGGED_TRANSACTIONS';
