export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_A_USER_PROFILE = 'GET_A_USER_PROFILE';
export const EDIT_A_USER_PROFILE = 'EDIT_A_USER_PROFILE';
export const DETACH_PROGRAMME = 'DETACH_PROGRAMME';
